### PR TITLE
Add login() function

### LINKED ISSUE #1: Finalize meditor ("Edit metadata") webshotting
there is already a stab https://github.com/dandi/dandi-api-webshots/blob/master/tools/make_webshots.py#L49 but we would need to have authenticated session (based on having `DANDI_API_KEY` env var provided) to be able to enter meditor for a dataset for a user which either has admin privileges or just owns a specific dandiset.

### PR DESCRIPTION
**Pull request by jwodder**
Closes #1.

Replaces #10.

### CODE REVIEW

**Comment by jwodder** [comment]
@yarikoptic The good news is that entering the username & password works now.  The bad news is that GitHub is now asking for a device verification code.

**Comment by yarikoptic** [comment]
I replied via email about that - we might need to try transplanting a cookie if that is possible

**Comment by jwodder** [comment]
@yarikoptic I highly doubt that would work.  The cookie is almost certainly mapped to the specific browser.

**Comment by yarikoptic** [comment]
It is just a record, I don't think it has any magical glue to a browser in it. There is even selenium support for setting them https://www.selenium.dev/documentation/en/support_packages/working_with_cookies/

**Comment by yarikoptic** [comment]
What might happen is that the value in this particular case is somehow bound to the specific instance of a browser (as it presents itself to git hub) but that is yet to be checked and also unlikely ;-)

**Comment by yarikoptic** [comment]
device verification dialog is still on so needs more digging

**Pull request merged**
